# Generated by Django 6.0.4 on 2026-05-03 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='name',
            new_name='user',
        ),
    ]
